-- Run this in your Supabase SQL editor (https://supabase.com/dashboard/project/shbkpqqpmllhognnaixv/sql/new)

-- Upvotes
create table if not exists upvotes (
  id bigint generated by default as identity primary key,
  target_type text not null, -- 'curated' or 'community'
  target_id text not null, -- slug or public_id
  session_id text not null,
  direction text not null, -- 'up' or 'down'
  created_at timestamp with time zone default now(),
  unique(target_type, target_id, session_id)
);

-- Downloads
create table if not exists downloads (
  id bigint generated by default as identity primary key,
  target_type text not null,
  target_id text not null,
  session_id text not null,
  created_at timestamp with time zone default now()
);

-- Favorites
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  target_type text not null,
  target_id text not null,
  session_id text not null,
  created_at timestamp with time zone default now(),
  unique(target_type, target_id, session_id)
);

-- Comments
create table if not exists comments (
  id bigint generated by default as identity primary key,
  target_type text not null,
  target_id text not null,
  author text default 'anonymous',
  body text not null,
  created_at timestamp with time zone default now()
);

-- Enable RLS (safe by default)
alter table upvotes enable row level security;
alter table downloads enable row level security;
alter table favorites enable row level security;
alter table comments enable row level security;

-- Allow anonymous access (no auth required)
create policy "anon insert upvotes" on upvotes for insert to anon with check (true);
create policy "anon select upvotes" on upvotes for select to anon using (true);
create policy "anon delete upvotes" on upvotes for delete to anon using (true);

create policy "anon insert downloads" on downloads for insert to anon with check (true);
create policy "anon select downloads" on downloads for select to anon using (true);

create policy "anon insert favorites" on favorites for insert to anon with check (true);
create policy "anon select favorites" on favorites for select to anon using (true);
create policy "anon delete favorites" on favorites for delete to anon using (true);

create policy "anon insert comments" on comments for insert to anon with check (true);
create policy "anon select comments" on comments for select to anon using (true);

-- Reports
create table if not exists reports (
  id bigint generated by default as identity primary key,
  url text not null,
  issue text not null,
  notes text default '',
  page text not null,
  created_at timestamp with time zone default now()
);

alter table reports enable row level security;
create policy "anon insert reports" on reports for insert to anon with check (true);
create policy "anon select reports" on reports for select to anon using (true);
